id: I598307E6
legacy_id: P006639
ocr_import_info:
  bdrc_scan_id: W1CZ1137
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T12:07:27'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T18:56:38.558101+00:00'
last_modified: 2022-08-31 02:56:50.749827
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1137
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1137
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བླ་མ་མཆོད་པའི་ཆོ་ག་དངོས་གྲུབ་རིན་པོ་ཆེའི་གཏེར་མཛོད།
  author: འཇམ་དབྱངས་མཁྱེན་བརྩེའི་དབང་ཕྱུག་བསྟན་པའི་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.561847826441669
  ocr_word_median_confidence_index: 0.5400000214576721
quality: null
bases:
  I1CZ1534:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1534
      total_pages: 24
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ1534.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.561847826441669
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
